export const carData = [
  {
    licensePlate: "ABC987",
    companyName: "Volkswagen",
    category: "Car Loan",
    carDetails: "Jetta GLI Autobahn - Pure White",
    date: "2022-01-15",
    model: "Jetta",
    mileage: 15000,
    buyingPrice: 24000,
    imageUrl: "https://source.unsplash.com/featured/?volkswagen,jetta",
  },
  {
    licensePlate: "XYZ321",
    companyName: "Acura",
    category: "Car Loan",
    carDetails: "ILX Premium Package - Modern Steel Metallic",
    date: "2022-02-20",
    model: "ILX",
    mileage: 18000,
    buyingPrice: 28000,
    imageUrl: "https://source.unsplash.com/featured/?acura,ilx",
  },
  {
    licensePlate: "DEF123",
    companyName: "Kia",
    category: "Car Loan",
    carDetails: "Optima SX - Ebony Black",
    date: "2022-03-10",
    model: "Optima",
    mileage: 20000,
    buyingPrice: 25000,
    imageUrl: "https://source.unsplash.com/featured/?kia,optima",
  },
  {
    licensePlate: "PQR123",
    companyName: "Infiniti",
    category: "Car Loan",
    carDetails: "Q50 Luxe - Majestic White",
    date: "2022-04-05",
    model: "Q50",
    mileage: 18000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?infiniti,q50",
  },
  {
    licensePlate: "GHI987",
    companyName: "Cadillac",
    category: "Car Loan",
    carDetails: "CTS Luxury - Radiant Silver Metallic",
    date: "2022-05-12",
    model: "CTS",
    mileage: 20000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?cadillac,cts",
  },
  {
    licensePlate: "LMN123",
    companyName: "Mitsubishi",
    category: "Car Loan",
    carDetails: "Outlander SEL - Labrador Black Metallic",
    date: "2022-06-18",
    model: "Outlander",
    mileage: 22000,
    buyingPrice: 27000,
    imageUrl: "https://source.unsplash.com/featured/?mitsubishi,outlander",
  },
  {
    licensePlate: "VWX987",
    companyName: "Genesis",
    category: "Car Loan",
    carDetails: "G70 3.3T Sport - Himalayan Gray",
    date: "2022-07-02",
    model: "G70",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?genesis,g70",
  },
  {
    licensePlate: "STU654",
    companyName: "Jaguar",
    category: "Car Loan",
    carDetails: "XE S - Yulong White Metallic",
    date: "2022-08-22",
    model: "XE",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?jaguar,xe",
  },
  {
    licensePlate: "JKL987",
    companyName: "Buick",
    category: "Car Loan",
    carDetails: "Regal Sportback Essence - Quicksilver Metallic",
    date: "2022-09-14",
    model: "Regal Sportback",
    mileage: 22000,
    buyingPrice: 30000,
    imageUrl: "https://source.unsplash.com/featured/?buick,regal",
  },
  {
    licensePlate: "MNO456",
    companyName: "Chrysler",
    category: "Car Loan",
    carDetails: "300 Touring - Bright White Clearcoat",
    date: "2022-10-30",
    model: "300",
    mileage: 25000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?chrysler,300",
  },
  {
    licensePlate: "XYZ456",
    companyName: "Chevrolet",
    category: "Car Loan",
    carDetails: "Silverado 1500 LTZ - Summit White",
    date: "2022-01-15",
    model: "Silverado 1500",
    mileage: 40000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?chevrolet,silverado",
  },
  {
    licensePlate: "DEF789",
    companyName: "Honda",
    category: "Car Loan",
    carDetails: "Pilot EX-L AWD - Modern Steel Metallic",
    date: "2022-02-20",
    model: "Pilot",
    mileage: 35000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?honda,pilot",
  },
  {
    licensePlate: "JKL987",
    companyName: "GMC",
    category: "Car Loan",
    carDetails: "Sierra 1500 Denali - Onyx Black",
    date: "2022-03-10",
    model: "Sierra 1500",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?gmc,sierra",
  },
  {
    licensePlate: "MNO123",
    companyName: "Hyundai",
    category: "Car Loan",
    carDetails: "Santa Fe Limited - Twilight Black",
    date: "2022-04-05",
    model: "Santa Fe",
    mileage: 20000,
    buyingPrice: 33000,
    imageUrl: "https://source.unsplash.com/featured/?hyundai,santafe",
  },
  {
    licensePlate: "PQR789",
    companyName: "Jeep",
    category: "Car Loan",
    carDetails: "Grand Cherokee Limited - Diamond Black Crystal Pearl",
    date: "2022-05-12",
    model: "Grand Cherokee",
    mileage: 30000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?jeep,grandcherokee",
  },
  {
    licensePlate: "GHI321",
    companyName: "Ram",
    category: "Car Loan",
    carDetails: "1500 Big Horn Crew Cab - Bright White Clearcoat",
    date: "2022-06-18",
    model: "Ram 1500",
    mileage: 40000,
    buyingPrice: 36000,
    imageUrl: "https://source.unsplash.com/featured/?ram,1500",
  },
  {
    licensePlate: "LMN456",
    companyName: "Mercedes-Benz",
    category: "Car Loan",
    carDetails: "GLE 350 4MATIC - Polar White",
    date: "2022-07-02",
    model: "GLE",
    mileage: 25000,
    buyingPrice: 50000,
    imageUrl: "https://source.unsplash.com/featured/?mercedes,gle",
  },
  {
    licensePlate: "VWX987",
    companyName: "Lexus",
    category: "Car Loan",
    carDetails: "RX 350 - Atomic Silver",
    date: "2022-08-22",
    model: "RX",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?lexus,rx",
  },
  {
    licensePlate: "STU654",
    companyName: "Subaru",
    category: "Car Loan",
    carDetails: "Outback Limited XT - Abyss Blue Pearl",
    date: "2022-09-14",
    model: "Outback",
    mileage: 22000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?subaru,outback",
  },
  {
    licensePlate: "ABC123",
    companyName: "Toyota",
    category: "Cars & Truck",
    carDetails: "1.8 G CVT - Platinum White Pearl Mica",
    date: "2022-10-30",
    model: "Camry",
    mileage: 50000,
    buyingPrice: 25000,
    imageUrl: "https://source.unsplash.com/featured/?toyota,camry",
  },
  {
    licensePlate: "XYZ789",
    companyName: "Honda",
    category: "Cars & Truck",
    carDetails: "EX-L AWD - Modern Steel Metallic",
    date: "2022-01-15",
    model: "CR-V",
    mileage: 30000,
    buyingPrice: 30000,
    imageUrl: "https://source.unsplash.com/featured/?honda,crv",
  },
  {
    licensePlate: "DEF456",
    companyName: "Ford",
    category: "Cars & Truck",
    carDetails: "Lariat SuperCrew 4x4 - Oxford White",
    date: "2022-02-20",
    model: "F-150",
    mileage: 70000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?ford,f150",
  },
  {
    licensePlate: "JKL321",
    companyName: "Chevrolet",
    category: "Cars & Truck",
    carDetails: "LT - Summit White",
    date: "2022-03-10",
    model: "Spark",
    mileage: 40000,
    buyingPrice: 20000,
    imageUrl: "https://source.unsplash.com/featured/?chevrolet,spark",
  },
  {
    licensePlate: "MNO987",
    companyName: "BMW",
    category: "Cars & Truck",
    carDetails: "M4 Competition - Sapphire Black Metallic",
    date: "2022-04-05",
    model: "M4",
    mileage: 20000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?bmw,m4",
  },
  {
    licensePlate: "PQR654",
    companyName: "Nissan",
    category: "Cars & Truck",
    carDetails: "Sport Touring - Deep Blue Pearl",
    date: "2022-05-12",
    model: "370Z",
    mileage: 60000,
    buyingPrice: 30000,
    imageUrl: "https://source.unsplash.com/featured/?nissan,370z",
  },
  {
    licensePlate: "GHI789",
    companyName: "Toyota",
    category: "Cars & Truck",
    carDetails: "2.0 Hybrid - Lunar Rock",
    date: "2022-06-18",
    model: "Corolla",
    mileage: 35000,
    buyingPrice: 27000,
    imageUrl: "https://source.unsplash.com/featured/?toyota,corolla",
  },
  {
    licensePlate: "UVW123",
    companyName: "Mazda",
    category: "Cars & Truck",
    carDetails: "CX-5 Touring - Eternal Blue Mica",
    date: "2022-07-02",
    model: "CX-5",
    mileage: 25000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?mazda,cx5",
  },
  {
    licensePlate: "STU456",
    companyName: "Audi",
    category: "Cars & Truck",
    carDetails: "A5 Quattro - Mythos Black Metallic",
    date: "2022-08-22",
    model: "A5",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?audi,a5",
  },
  {
    licensePlate: "XYZ987",
    companyName: "Tesla",
    category: "Cars & Truck",
    carDetails: "Model 3 Long Range - Midnight Silver Metallic",
    date: "2022-09-14",
    model: "Model 3",
    mileage: 10000,
    buyingPrice: 50000,
    imageUrl: "https://source.unsplash.com/featured/?tesla,model3",
  },
  {
    licensePlate: "ABC567",
    companyName: "Ford",
    category: "Cars & Truck",
    carDetails: "Escape SE - Oxford White",
    date: "2022-10-30",
    model: "Escape",
    mileage: 30000,
    buyingPrice: 28000,
    imageUrl: "https://source.unsplash.com/featured/?ford,escape",
  },
  {
    licensePlate: "XYZ456",
    companyName: "Chevrolet",
    category: "Cars & Truck",
    carDetails: "Silverado 1500 LTZ - Summit White",
    date: "2022-01-15",
    model: "Silverado 1500",
    mileage: 40000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?chevrolet,silverado",
  },
  {
    licensePlate: "DEF789",
    companyName: "Honda",
    category: "Cars & Truck",
    carDetails: "Pilot EX-L AWD - Modern Steel Metallic",
    date: "2022-02-20",
    model: "Pilot",
    mileage: 35000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?honda,pilot",
  },
  {
    licensePlate: "JKL987",
    companyName: "GMC",
    category: "Cars & Truck",
    carDetails: "Sierra 1500 Denali - Onyx Black",
    date: "2022-03-10",
    model: "Sierra 1500",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?gmc,sierra",
  },
  {
    licensePlate: "MNO123",
    companyName: "Hyundai",
    category: "Cars & Truck",
    carDetails: "Santa Fe Limited - Twilight Black",
    date: "2022-04-05",
    model: "Santa Fe",
    mileage: 20000,
    buyingPrice: 33000,
    imageUrl: "https://source.unsplash.com/featured/?hyundai,santafe",
  },
  {
    licensePlate: "PQR789",
    companyName: "Jeep",
    category: "Cars & Truck",
    carDetails: "Grand Cherokee Limited - Diamond Black Crystal Pearl",
    date: "2022-05-12",
    model: "Grand Cherokee",
    mileage: 30000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?jeep,grandcherokee",
  },
  {
    licensePlate: "GHI321",
    companyName: "Ram",
    category: "Cars & Truck",
    carDetails: "1500 Big Horn Crew Cab - Bright White Clearcoat",
    date: "2022-06-18",
    model: "Ram 1500",
    mileage: 40000,
    buyingPrice: 36000,
    imageUrl: "https://source.unsplash.com/featured/?ram,1500",
  },
  {
    licensePlate: "LMN456",
    companyName: "Mercedes-Benz",
    category: "Cars & Truck",
    carDetails: "GLE 350 4MATIC - Polar White",
    date: "2022-07-02",
    model: "GLE",
    mileage: 25000,
    buyingPrice: 50000,
    imageUrl: "https://source.unsplash.com/featured/?mercedes,gle",
  },
  {
    licensePlate: "VWX987",
    companyName: "Lexus",
    category: "Cars & Truck",
    carDetails: "RX 350 - Atomic Silver",
    date: "2022-08-22",
    model: "RX",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?lexus,rx",
  },
  {
    licensePlate: "STU654",
    companyName: "Subaru",
    category: "Cars & Truck",
    carDetails: "Outback Limited XT - Abyss Blue Pearl",
    date: "2022-09-14",
    model: "Outback",
    mileage: 22000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?subaru,outback",
  },
];


export const carloanData = [
  {
    licensePlate: "ABC987",
    companyName: "Volkswagen",
    category: "Car Loan",
    carDetails: "Jetta GLI Autobahn - Pure White",
    date: "2022-10-30",
    model: "Jetta",
    mileage: 15000,
    buyingPrice: 24000,
    imageUrl: "https://source.unsplash.com/featured/?volkswagen,jetta",
  },
  {
    licensePlate: "XYZ321",
    companyName: "Acura",
    category: "Car Loan",
    carDetails: "ILX Premium Package - Modern Steel Metallic",
    model: "ILX",
    mileage: 18000,
    buyingPrice: 28000,
    imageUrl: "https://source.unsplash.com/featured/?acura,ilx",
  },
  {
    licensePlate: "DEF123",
    companyName: "Kia",
    category: "Car Loan",
    carDetails: "Optima SX - Ebony Black",
    model: "Optima",
    mileage: 20000,
    buyingPrice: 25000,
    imageUrl: "https://source.unsplash.com/featured/?kia,optima",
  },
  {
    licensePlate: "PQR123",
    companyName: "Infiniti",
    category: "Car Loan",
    carDetails: "Q50 Luxe - Majestic White",
    model: "Q50",
    mileage: 18000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?infiniti,q50",
  },
  {
    licensePlate: "GHI987",
    companyName: "Cadillac",
    category: "Car Loan",
    carDetails: "CTS Luxury - Radiant Silver Metallic",
    model: "CTS",
    mileage: 20000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?cadillac,cts",
  },
  {
    licensePlate: "LMN123",
    companyName: "Mitsubishi",
    category: "Car Loan",
    carDetails: "Outlander SEL - Labrador Black Metallic",
    model: "Outlander",
    mileage: 22000,
    buyingPrice: 27000,
    imageUrl: "https://source.unsplash.com/featured/?mitsubishi,outlander",
  },
  {
    licensePlate: "VWX987",
    companyName: "Genesis",
    category: "Car Loan",
    carDetails: "G70 3.3T Sport - Himalayan Gray",
    model: "G70",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?genesis,g70",
  },
  {
    licensePlate: "STU654",
    companyName: "Jaguar",
    category: "Car Loan",
    carDetails: "XE S - Yulong White Metallic",
    model: "XE",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?jaguar,xe",
  },
  {
    licensePlate: "JKL987",
    companyName: "Buick",
    category: "Car Loan",
    carDetails: "Regal Sportback Essence - Quicksilver Metallic",
    model: "Regal Sportback",
    mileage: 22000,
    buyingPrice: 30000,
    imageUrl: "https://source.unsplash.com/featured/?buick,regal",
  },
  {
    licensePlate: "MNO456",
    companyName: "Chrysler",
    category: "Car Loan",
    carDetails: "300 Touring - Bright White Clearcoat",
    model: "300",
    mileage: 25000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?chrysler,300",
  },
  {
    licensePlate: "XYZ456",
    companyName: "Chevrolet",
    category: "Car Loan",
    carDetails: "Silverado 1500 LTZ - Summit White",
    model: "Silverado 1500",
    mileage: 40000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?chevrolet,silverado",
  },
  {
    licensePlate: "DEF789",
    companyName: "Honda",
    category: "Car Loan",
    carDetails: "Pilot EX-L AWD - Modern Steel Metallic",
    model: "Pilot",
    mileage: 35000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?honda,pilot",
  },
  {
    licensePlate: "JKL987",
    companyName: "GMC",
    category: "Car Loan",
    carDetails: "Sierra 1500 Denali - Onyx Black",
    model: "Sierra 1500",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?gmc,sierra",
  },
  {
    licensePlate: "MNO123",
    companyName: "Hyundai",
    category: "Car Loan",
    carDetails: "Santa Fe Limited - Twilight Black",
    model: "Santa Fe",
    mileage: 20000,
    buyingPrice: 33000,
    imageUrl: "https://source.unsplash.com/featured/?hyundai,santafe",
  },
  {
    licensePlate: "PQR789",
    companyName: "Jeep",
    category: "Car Loan",
    carDetails: "Grand Cherokee Limited - Diamond Black Crystal Pearl",
    model: "Grand Cherokee",
    mileage: 30000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?jeep,grandcherokee",
  },
  {
    licensePlate: "GHI321",
    companyName: "Ram",
    category: "Car Loan",
    carDetails: "1500 Big Horn Crew Cab - Bright White Clearcoat",
    model: "Ram 1500",
    mileage: 40000,
    buyingPrice: 36000,
    imageUrl: "https://source.unsplash.com/featured/?ram,1500",
  },
  {
    licensePlate: "LMN456",
    companyName: "Mercedes-Benz",
    category: "Car Loan",
    carDetails: "GLE 350 4MATIC - Polar White",
    model: "GLE",
    mileage: 25000,
    buyingPrice: 50000,
    imageUrl: "https://source.unsplash.com/featured/?mercedes,gle",
  },
  {
    licensePlate: "VWX987",
    companyName: "Lexus",
    category: "Car Loan",
    carDetails: "RX 350 - Atomic Silver",
    model: "RX",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?lexus,rx",
  },
  {
    licensePlate: "STU654",
    companyName: "Subaru",
    category: "Car Loan",
    carDetails: "Outback Limited XT - Abyss Blue Pearl",
    model: "Outback",
    mileage: 22000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?subaru,outback",
  },
];

 export const postData = [
 {
    imageUrl: 'https://source.unsplash.com/featured/?car',
    content: 'Just bought a new car! 🚗 #Excited #NewCar #CityLife #UrbanExplore',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?automobile',
    content: 'Road trip vibes! Where should I go next? 🛣️ #RoadTrip #Adventure',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?vehicle',
    content: 'Car goals achieved! Dream car in my driveway. 😍 #DreamCar #Achievement',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?sportscar',
    content: 'Feeling the need for speed! Zooming through the city in my new sports car. 🏎️ #FastAndFurious',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?luxurycar',
    content: 'Living the luxury life with my new ride. Class and comfort all the way. 🌟 #LuxuryCar #Style',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?pickuptruck',
    content: 'Got a pickup truck for those heavy-duty tasks. Ready for some serious work! 💪 #Workhorse #TruckLife',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?electriccar',
    content: 'Embracing the future with my new electric car. Zero emissions, all the fun! ⚡🌍 #ElectricCar',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?vintagecar',
    content: 'Cruising in style with my vintage car. Old is gold! 🚗✨ #VintageCar #ClassicBeauty',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?convertible',
    content: 'Top-down, wind in my hair—nothing beats the feeling of driving a convertible. 🌞 #ConvertibleLife',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?familycar',
    content: 'Family adventures await with our new spacious family car. Making memories on the road. 👨‍👩‍👧‍👦 #FamilyTime',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?suv',
    content: 'SUV life! Off-roading and exploring the great outdoors. 🌲🏞️ #SUVAdventures #ExploreNature',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?supercar',
    content: 'Feeling like a superhero in my new supercar. Ready to conquer the streets! 🦸‍♂️🏎️ #SuperCar #PowerfulRide',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?racecar',
    content: 'Living life in the fast lane with my new racecar. Speed, precision, and adrenaline! 🏁 #RaceCar',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?pickup',
    content: 'Picked up a pickup for weekend projects and outdoor adventures. Versatile and reliable! 🛠️🏕️ #PickupLife',
  },
  {
    imageUrl: 'https://source.unsplash.com/featured/?citycar',
    content: 'Navigating the urban jungle with my sleek city car. Stylish and efficient! 🏙️🚗 #CityLife #UrbanExplorer',
  },
];

export const lineData = [
  {
    "company": "Volkswagen",
    "revenue": 64854,
    "cost": 32652
  },
  {
    "company": "Acura",
    "revenue": 54628,
    "cost": 42393
  },
  {
    "company": "Kia",
    "revenue": 117238,
    "cost": 50262
  },
  {
    "company": "Infiniti",
    "revenue": 82830,
    "cost": 64731
  },
  {
    "company": "Cadillac",
    "revenue": 91208,
    "cost": 41893
  },
  {
    "company": "Mitsubishi",
    "revenue": 103609,
    "cost": 83809
  },
  {
    "company": "Genesis",
    "revenue": 90974,
    "cost": 44772
  },
  {
    "company": "Jaguar",
    "revenue": 82919,
    "cost": 37590
  },
  {
    "company": "Buick",
    "revenue": 62407,
    "cost": 43349
  },
  {
    "company": "Chrysler",
    "revenue": 82528,
    "cost": 45324
  },
  {
    "company": "Chevrolet",
    "revenue": 56979,
    "cost": 47978
  },
  {
    "company": "Honda",
    "revenue": 87436,
    "cost": 39175
  }
]

