export const carData = [
  {
    licensePlate: "ABC987",
    companyName: "Volkswagen",
    category: "Car Loan",
    carDetails: "Jetta GLI Autobahn - Pure White",
    date: "2022-01-15",
    model: "Jetta",
    mileage: 15000,
    buyingPrice: 24000,
    imageUrl: "https://source.unsplash.com/featured/?volkswagen,jetta",
  },
  {
    licensePlate: "XYZ321",
    companyName: "Acura",
    category: "Car Loan",
    carDetails: "ILX Premium Package - Modern Steel Metallic",
    date: "2022-02-20",
    model: "ILX",
    mileage: 18000,
    buyingPrice: 28000,
    imageUrl: "https://source.unsplash.com/featured/?acura,ilx",
  },
  {
    licensePlate: "DEF123",
    companyName: "Kia",
    category: "Car Loan",
    carDetails: "Optima SX - Ebony Black",
    date: "2022-03-10",
    model: "Optima",
    mileage: 20000,
    buyingPrice: 25000,
    imageUrl: "https://source.unsplash.com/featured/?kia,optima",
  },
  {
    licensePlate: "PQR123",
    companyName: "Infiniti",
    category: "Car Loan",
    carDetails: "Q50 Luxe - Majestic White",
    date: "2022-04-05",
    model: "Q50",
    mileage: 18000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?infiniti,q50",
  },
  {
    licensePlate: "GHI987",
    companyName: "Cadillac",
    category: "Car Loan",
    carDetails: "CTS Luxury - Radiant Silver Metallic",
    date: "2022-05-12",
    model: "CTS",
    mileage: 20000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?cadillac,cts",
  },
  {
    licensePlate: "LMN123",
    companyName: "Mitsubishi",
    category: "Car Loan",
    carDetails: "Outlander SEL - Labrador Black Metallic",
    date: "2022-06-18",
    model: "Outlander",
    mileage: 22000,
    buyingPrice: 27000,
    imageUrl: "https://source.unsplash.com/featured/?mitsubishi,outlander",
  },
  {
    licensePlate: "VWX987",
    companyName: "Genesis",
    category: "Car Loan",
    carDetails: "G70 3.3T Sport - Himalayan Gray",
    date: "2022-07-02",
    model: "G70",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?genesis,g70",
  },
  {
    licensePlate: "STU654",
    companyName: "Jaguar",
    category: "Car Loan",
    carDetails: "XE S - Yulong White Metallic",
    date: "2022-08-22",
    model: "XE",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?jaguar,xe",
  },
  {
    licensePlate: "JKL987",
    companyName: "Buick",
    category: "Car Loan",
    carDetails: "Regal Sportback Essence - Quicksilver Metallic",
    date: "2022-09-14",
    model: "Regal Sportback",
    mileage: 22000,
    buyingPrice: 30000,
    imageUrl: "https://source.unsplash.com/featured/?buick,regal",
  },
  {
    licensePlate: "MNO456",
    companyName: "Chrysler",
    category: "Car Loan",
    carDetails: "300 Touring - Bright White Clearcoat",
    date: "2022-10-30",
    model: "300",
    mileage: 25000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?chrysler,300",
  },
  {
    licensePlate: "XYZ456",
    companyName: "Chevrolet",
    category: "Car Loan",
    carDetails: "Silverado 1500 LTZ - Summit White",
    date: "2022-01-15",
    model: "Silverado 1500",
    mileage: 40000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?chevrolet,silverado",
  },
  {
    licensePlate: "DEF789",
    companyName: "Honda",
    category: "Car Loan",
    carDetails: "Pilot EX-L AWD - Modern Steel Metallic",
    date: "2022-02-20",
    model: "Pilot",
    mileage: 35000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?honda,pilot",
  },
  {
    licensePlate: "JKL987",
    companyName: "GMC",
    category: "Car Loan",
    carDetails: "Sierra 1500 Denali - Onyx Black",
    date: "2022-03-10",
    model: "Sierra 1500",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?gmc,sierra",
  },
  {
    licensePlate: "MNO123",
    companyName: "Hyundai",
    category: "Car Loan",
    carDetails: "Santa Fe Limited - Twilight Black",
    date: "2022-04-05",
    model: "Santa Fe",
    mileage: 20000,
    buyingPrice: 33000,
    imageUrl: "https://source.unsplash.com/featured/?hyundai,santafe",
  },
  {
    licensePlate: "PQR789",
    companyName: "Jeep",
    category: "Car Loan",
    carDetails: "Grand Cherokee Limited - Diamond Black Crystal Pearl",
    date: "2022-05-12",
    model: "Grand Cherokee",
    mileage: 30000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?jeep,grandcherokee",
  },
  {
    licensePlate: "GHI321",
    companyName: "Ram",
    category: "Car Loan",
    carDetails: "1500 Big Horn Crew Cab - Bright White Clearcoat",
    date: "2022-06-18",
    model: "Ram 1500",
    mileage: 40000,
    buyingPrice: 36000,
    imageUrl: "https://source.unsplash.com/featured/?ram,1500",
  },
  {
    licensePlate: "LMN456",
    companyName: "Mercedes-Benz",
    category: "Car Loan",
    carDetails: "GLE 350 4MATIC - Polar White",
    date: "2022-07-02",
    model: "GLE",
    mileage: 25000,
    buyingPrice: 50000,
    imageUrl: "https://source.unsplash.com/featured/?mercedes,gle",
  },
  {
    licensePlate: "VWX987",
    companyName: "Lexus",
    category: "Car Loan",
    carDetails: "RX 350 - Atomic Silver",
    date: "2022-08-22",
    model: "RX",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?lexus,rx",
  },
  {
    licensePlate: "STU654",
    companyName: "Subaru",
    category: "Car Loan",
    carDetails: "Outback Limited XT - Abyss Blue Pearl",
    date: "2022-09-14",
    model: "Outback",
    mileage: 22000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?subaru,outback",
  },
  {
    licensePlate: "ABC123",
    companyName: "Toyota",
    category: "Cars & Truck",
    carDetails: "1.8 G CVT - Platinum White Pearl Mica",
    date: "2022-10-30",
    model: "Camry",
    mileage: 50000,
    buyingPrice: 25000,
    imageUrl: "https://source.unsplash.com/featured/?toyota,camry",
  },
  {
    licensePlate: "XYZ789",
    companyName: "Honda",
    category: "Cars & Truck",
    carDetails: "EX-L AWD - Modern Steel Metallic",
    date: "2022-01-15",
    model: "CR-V",
    mileage: 30000,
    buyingPrice: 30000,
    imageUrl: "https://source.unsplash.com/featured/?honda,crv",
  },
  {
    licensePlate: "DEF456",
    companyName: "Ford",
    category: "Cars & Truck",
    carDetails: "Lariat SuperCrew 4x4 - Oxford White",
    date: "2022-02-20",
    model: "F-150",
    mileage: 70000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?ford,f150",
  },
  {
    licensePlate: "JKL321",
    companyName: "Chevrolet",
    category: "Cars & Truck",
    carDetails: "LT - Summit White",
    date: "2022-03-10",
    model: "Spark",
    mileage: 40000,
    buyingPrice: 20000,
    imageUrl: "https://source.unsplash.com/featured/?chevrolet,spark",
  },
  {
    licensePlate: "MNO987",
    companyName: "BMW",
    category: "Cars & Truck",
    carDetails: "M4 Competition - Sapphire Black Metallic",
    date: "2022-04-05",
    model: "M4",
    mileage: 20000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?bmw,m4",
  },
  {
    licensePlate: "PQR654",
    companyName: "Nissan",
    category: "Cars & Truck",
    carDetails: "Sport Touring - Deep Blue Pearl",
    date: "2022-05-12",
    model: "370Z",
    mileage: 60000,
    buyingPrice: 30000,
    imageUrl: "https://source.unsplash.com/featured/?nissan,370z",
  },
  {
    licensePlate: "GHI789",
    companyName: "Toyota",
    category: "Cars & Truck",
    carDetails: "2.0 Hybrid - Lunar Rock",
    date: "2022-06-18",
    model: "Corolla",
    mileage: 35000,
    buyingPrice: 27000,
    imageUrl: "https://source.unsplash.com/featured/?toyota,corolla",
  },
  {
    licensePlate: "UVW123",
    companyName: "Mazda",
    category: "Cars & Truck",
    carDetails: "CX-5 Touring - Eternal Blue Mica",
    date: "2022-07-02",
    model: "CX-5",
    mileage: 25000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?mazda,cx5",
  },
  {
    licensePlate: "STU456",
    companyName: "Audi",
    category: "Cars & Truck",
    carDetails: "A5 Quattro - Mythos Black Metallic",
    date: "2022-08-22",
    model: "A5",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?audi,a5",
  },
  {
    licensePlate: "XYZ987",
    companyName: "Tesla",
    category: "Cars & Truck",
    carDetails: "Model 3 Long Range - Midnight Silver Metallic",
    date: "2022-09-14",
    model: "Model 3",
    mileage: 10000,
    buyingPrice: 50000,
    imageUrl: "https://source.unsplash.com/featured/?tesla,model3",
  },
  {
    licensePlate: "ABC567",
    companyName: "Ford",
    category: "Cars & Truck",
    carDetails: "Escape SE - Oxford White",
    date: "2022-10-30",
    model: "Escape",
    mileage: 30000,
    buyingPrice: 28000,
    imageUrl: "https://source.unsplash.com/featured/?ford,escape",
  },
  {
    licensePlate: "XYZ456",
    companyName: "Chevrolet",
    category: "Cars & Truck",
    carDetails: "Silverado 1500 LTZ - Summit White",
    date: "2022-01-15",
    model: "Silverado 1500",
    mileage: 40000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?chevrolet,silverado",
  },
  {
    licensePlate: "DEF789",
    companyName: "Honda",
    category: "Cars & Truck",
    carDetails: "Pilot EX-L AWD - Modern Steel Metallic",
    date: "2022-02-20",
    model: "Pilot",
    mileage: 35000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?honda,pilot",
  },
  {
    licensePlate: "JKL987",
    companyName: "GMC",
    category: "Cars & Truck",
    carDetails: "Sierra 1500 Denali - Onyx Black",
    date: "2022-03-10",
    model: "Sierra 1500",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?gmc,sierra",
  },
  {
    licensePlate: "MNO123",
    companyName: "Hyundai",
    category: "Cars & Truck",
    carDetails: "Santa Fe Limited - Twilight Black",
    date: "2022-04-05",
    model: "Santa Fe",
    mileage: 20000,
    buyingPrice: 33000,
    imageUrl: "https://source.unsplash.com/featured/?hyundai,santafe",
  },
  {
    licensePlate: "PQR789",
    companyName: "Jeep",
    category: "Cars & Truck",
    carDetails: "Grand Cherokee Limited - Diamond Black Crystal Pearl",
    date: "2022-05-12",
    model: "Grand Cherokee",
    mileage: 30000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?jeep,grandcherokee",
  },
  {
    licensePlate: "GHI321",
    companyName: "Ram",
    category: "Cars & Truck",
    carDetails: "1500 Big Horn Crew Cab - Bright White Clearcoat",
    date: "2022-06-18",
    model: "Ram 1500",
    mileage: 40000,
    buyingPrice: 36000,
    imageUrl: "https://source.unsplash.com/featured/?ram,1500",
  },
  {
    licensePlate: "LMN456",
    companyName: "Mercedes-Benz",
    category: "Cars & Truck",
    carDetails: "GLE 350 4MATIC - Polar White",
    date: "2022-07-02",
    model: "GLE",
    mileage: 25000,
    buyingPrice: 50000,
    imageUrl: "https://source.unsplash.com/featured/?mercedes,gle",
  },
  {
    licensePlate: "VWX987",
    companyName: "Lexus",
    category: "Cars & Truck",
    carDetails: "RX 350 - Atomic Silver",
    date: "2022-08-22",
    model: "RX",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?lexus,rx",
  },
  {
    licensePlate: "STU654",
    companyName: "Subaru",
    category: "Cars & Truck",
    carDetails: "Outback Limited XT - Abyss Blue Pearl",
    date: "2022-09-14",
    model: "Outback",
    mileage: 22000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?subaru,outback",
  },
];


export const carloanData = [
  {
    licensePlate: "ABC987",
    companyName: "Volkswagen",
    category: "Car Loan",
    carDetails: "Jetta GLI Autobahn - Pure White",
    date: "2022-10-30",
    model: "Jetta",
    mileage: 15000,
    buyingPrice: 24000,
    imageUrl: "https://source.unsplash.com/featured/?volkswagen,jetta",
  },
  {
    licensePlate: "XYZ321",
    companyName: "Acura",
    category: "Car Loan",
    carDetails: "ILX Premium Package - Modern Steel Metallic",
    model: "ILX",
    mileage: 18000,
    buyingPrice: 28000,
    imageUrl: "https://source.unsplash.com/featured/?acura,ilx",
  },
  {
    licensePlate: "DEF123",
    companyName: "Kia",
    category: "Car Loan",
    carDetails: "Optima SX - Ebony Black",
    model: "Optima",
    mileage: 20000,
    buyingPrice: 25000,
    imageUrl: "https://source.unsplash.com/featured/?kia,optima",
  },
  {
    licensePlate: "PQR123",
    companyName: "Infiniti",
    category: "Car Loan",
    carDetails: "Q50 Luxe - Majestic White",
    model: "Q50",
    mileage: 18000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?infiniti,q50",
  },
  {
    licensePlate: "GHI987",
    companyName: "Cadillac",
    category: "Car Loan",
    carDetails: "CTS Luxury - Radiant Silver Metallic",
    model: "CTS",
    mileage: 20000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?cadillac,cts",
  },
  {
    licensePlate: "LMN123",
    companyName: "Mitsubishi",
    category: "Car Loan",
    carDetails: "Outlander SEL - Labrador Black Metallic",
    model: "Outlander",
    mileage: 22000,
    buyingPrice: 27000,
    imageUrl: "https://source.unsplash.com/featured/?mitsubishi,outlander",
  },
  {
    licensePlate: "VWX987",
    companyName: "Genesis",
    category: "Car Loan",
    carDetails: "G70 3.3T Sport - Himalayan Gray",
    model: "G70",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?genesis,g70",
  },
  {
    licensePlate: "STU654",
    companyName: "Jaguar",
    category: "Car Loan",
    carDetails: "XE S - Yulong White Metallic",
    model: "XE",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?jaguar,xe",
  },
  {
    licensePlate: "JKL987",
    companyName: "Buick",
    category: "Car Loan",
    carDetails: "Regal Sportback Essence - Quicksilver Metallic",
    model: "Regal Sportback",
    mileage: 22000,
    buyingPrice: 30000,
    imageUrl: "https://source.unsplash.com/featured/?buick,regal",
  },
  {
    licensePlate: "MNO456",
    companyName: "Chrysler",
    category: "Car Loan",
    carDetails: "300 Touring - Bright White Clearcoat",
    model: "300",
    mileage: 25000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?chrysler,300",
  },
  {
    licensePlate: "XYZ456",
    companyName: "Chevrolet",
    category: "Car Loan",
    carDetails: "Silverado 1500 LTZ - Summit White",
    model: "Silverado 1500",
    mileage: 40000,
    buyingPrice: 35000,
    imageUrl: "https://source.unsplash.com/featured/?chevrolet,silverado",
  },
  {
    licensePlate: "DEF789",
    companyName: "Honda",
    category: "Car Loan",
    carDetails: "Pilot EX-L AWD - Modern Steel Metallic",
    model: "Pilot",
    mileage: 35000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?honda,pilot",
  },
  {
    licensePlate: "JKL987",
    companyName: "GMC",
    category: "Car Loan",
    carDetails: "Sierra 1500 Denali - Onyx Black",
    model: "Sierra 1500",
    mileage: 25000,
    buyingPrice: 40000,
    imageUrl: "https://source.unsplash.com/featured/?gmc,sierra",
  },
  {
    licensePlate: "MNO123",
    companyName: "Hyundai",
    category: "Car Loan",
    carDetails: "Santa Fe Limited - Twilight Black",
    model: "Santa Fe",
    mileage: 20000,
    buyingPrice: 33000,
    imageUrl: "https://source.unsplash.com/featured/?hyundai,santafe",
  },
  {
    licensePlate: "PQR789",
    companyName: "Jeep",
    category: "Car Loan",
    carDetails: "Grand Cherokee Limited - Diamond Black Crystal Pearl",
    model: "Grand Cherokee",
    mileage: 30000,
    buyingPrice: 38000,
    imageUrl: "https://source.unsplash.com/featured/?jeep,grandcherokee",
  },
  {
    licensePlate: "GHI321",
    companyName: "Ram",
    category: "Car Loan",
    carDetails: "1500 Big Horn Crew Cab - Bright White Clearcoat",
    model: "Ram 1500",
    mileage: 40000,
    buyingPrice: 36000,
    imageUrl: "https://source.unsplash.com/featured/?ram,1500",
  },
  {
    licensePlate: "LMN456",
    companyName: "Mercedes-Benz",
    category: "Car Loan",
    carDetails: "GLE 350 4MATIC - Polar White",
    model: "GLE",
    mileage: 25000,
    buyingPrice: 50000,
    imageUrl: "https://source.unsplash.com/featured/?mercedes,gle",
  },
  {
    licensePlate: "VWX987",
    companyName: "Lexus",
    category: "Car Loan",
    carDetails: "RX 350 - Atomic Silver",
    model: "RX",
    mileage: 18000,
    buyingPrice: 42000,
    imageUrl: "https://source.unsplash.com/featured/?lexus,rx",
  },
  {
    licensePlate: "STU654",
    companyName: "Subaru",
    category: "Car Loan",
    carDetails: "Outback Limited XT - Abyss Blue Pearl",
    model: "Outback",
    mileage: 22000,
    buyingPrice: 32000,
    imageUrl: "https://source.unsplash.com/featured/?subaru,outback",
  },
];

/* const carData = [
  {
    licensePlate: "ABC123",
    companyName: "Toyota",
    category: "Cars & Truck",
    carDetails: "1.8 G CVT - Platinum White Pearl Mica",
    model: "Camry",
    date: "2022-01-15",
    mileage: 50000,
    buyingPrice: 25000,
  },
  {
    licensePlate: "XYZ789",
    companyName: "Honda",
    category: "Cars & Truck",
    carDetails: "EX-L AWD - Modern Steel Metallic",
    model: "CR-V",
    date: "2022-02-20",
    mileage: 30000,
    buyingPrice: 30000,
  },
  {
    licensePlate: "DEF456",
    companyName: "Ford",
    category: "Cars & Truck",
    carDetails: "Lariat SuperCrew 4x4 - Oxford White",
    model: "F-150",
    date: "2022-03-10",
    mileage: 70000,
    buyingPrice: 35000,
  },
  {
    licensePlate: "JKL321",
    companyName: "Chevrolet",
    category: "Cars & Truck",
    carDetails: "LT - Summit White",
    model: "Spark",
    date: "2022-04-05",
    mileage: 40000,
    buyingPrice: 20000,
  },
  {
    licensePlate: "MNO987",
    companyName: "BMW",
    category: "Cars & Truck",
    carDetails: "M4 Competition - Sapphire Black Metallic",
    model: "M4",
    date: "2022-05-12",
    mileage: 20000,
    buyingPrice: 40000,
  },
  {
    licensePlate: "PQR654",
    companyName: "Nissan",
    category: "Cars & Truck",
    carDetails: "Sport Touring - Deep Blue Pearl",
    model: "370Z",
    date: "2022-06-18",
    mileage: 60000,
    buyingPrice: 30000,
  },
  {
    licensePlate: "GHI789",
    companyName: "Toyota",
    category: "Cars & Truck",
    carDetails: "2.0 Hybrid - Lunar Rock",
    model: "Corolla",
    date: "2022-07-02",
    mileage: 35000,
    buyingPrice: 27000,
  },
  {
    licensePlate: "UVW123",
    companyName: "Mazda",
    category: "Cars & Truck",
    carDetails: "CX-5 Touring - Eternal Blue Mica",
    model: "CX-5",
    date: "2022-08-22",
    mileage: 25000,
    buyingPrice: 32000,
  },
  {
    licensePlate: "STU456",
    companyName: "Audi",
    category: "Cars & Truck",
    carDetails: "A5 Quattro - Mythos Black Metallic",
    model: "A5",
    date: "2022-09-14",
    mileage: 18000,
    buyingPrice: 42000,
  },
  {
    licensePlate: "XYZ987",
    companyName: "Tesla",
    category: "Cars & Truck",
    carDetails: "Model 3 Long Range - Midnight Silver Metallic",
    model: "Model 3",
    date: "2022-10-30",
    mileage: 10000,
    buyingPrice: 50000,
  },
]; */
